#-----------------------------------------------------
#-----------Test Workflow YAML Pipeline for GitHub Actions
#-----------made by Eugene
name: My-GitHubActions-Test
env:
  APPLICATION_NAME       : "MyFlask"
  DEPLOY_PACKAGE_NAME    : "flask-deploy-ver-${{ github.sha}}"

on:
  push:
    branches:
      - main

jobs:
  my-test:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Testing job"
    - name: Execute few commands
      run : |
        echo "$APPLICATION_NAME"
        echo "${{ env.APPLICATION_NAME}}"
        echo "$DEPLOY_PACKAGE_NAME"
        echo "${{ env.DEPLOY_PACKAGE_NAME}}"
  my-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploying job"
  my-finish:
    runs-on: ubuntu-latest
    needs: [my-test, my-deploy]
    steps:
    - name: Print Finish Message
      run : echo "Finished successfully from Finish job"
    - name: Print DEPLOY_PACKAGE_NAME Message
      run : echo "$DEPLOY_PACKAGE_NAME Finished successfully"
